Q: QuitException in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/main.py", line 95, in kill_after_a_day
    selection = input("Q: Quit")
OSError: [Errno 9] Bad file descriptor
